(defun arithmetic-program ()
  (format t "Digite o Primeiro Numero: ")
  (let ((num1 (parse-integer (read-line))))
    (format t "Digite o Segundo Numero: ")
    (let ((num2 (parse-integer (read-line))))
      (let ((soma (+ num1 num2))
            (subtracao (- num1 num2))
            (multi (* num1 num2))
            (div (floor (/ num1 num2)))
            (res (mod num1 num2)))
