# Makefile para compilar e executar módulos Python

PYTHON = python3

.PHONY: all clean run_modulo1 run_modulo2

all: run_modulo1 run_modulo2

run_modulo1:
    $(PYTHON) src/modulo1.py

run_modulo2:
    $(PYTHON) src/modulo2.py

clean:
    # Comandos para limpar arquivos gerados, se houver
