# Makefile #


# Makefile para a cópia recursiva de arquivos

# Nome do arquivo Ruby
RUBY_FILE = copiar_recursivamente.rb

.PHONY: all copy clean

all: copy

copy:
	ruby $(RUBY_FILE) <origem> <destino>

clean:
	# Adicione comandos de limpeza aqui, se necessário
